FROM node:24-alpine

WORKDIR /app

RUN npm i -g pnpm

ENV PRISMA_SKIP_POSTINSTALL_GENERATE=true

ARG DATABASE_URL="postgresql://fake:fake@localhost:5432/fake"
ENV DATABASE_URL=$DATABASE_URL

COPY \
  package.json \
  pnpm-workspace.yaml \
  pnpm-lock.yaml \
  turbo.json \
  tsconfig.json \
  ./

COPY packages ./packages
COPY apps/frontend ./apps/frontend

RUN pnpm install

EXPOSE 3000

# dev
CMD ["pnpm", "--filter", "frontend", "dev", "--hostname", "0.0.0.0"]
